In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [2]:
file_path = '/content/drive/MyDrive/Colab Notebooks/CSE_151A/Proj1/credit_card_approval.csv'
df = pd.read_csv(file_path)
df.head()

ID CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY CNT_CHILDREN  \
0  5065438           F            Y               N  2+ children   
1  5142753           F            N               N  No children   
2  5111146           M            Y               Y  No children   
3  5010310           F            Y               Y   1 children   
4  5010835           M            Y               Y  2+ children   

   AMT_INCOME_TOTAL            NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  \
0          270000.0  Secondary / secondary special               Married   
1           81000.0  Secondary / secondary special  Single / not married   
2          270000.0               Higher education               Married   
3          112500.0  Secondary / secondary special               Married   
4          139500.0  Secondary / secondary special               Married   

   NAME_HOUSING_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  FLAG_MOBIL  FLAG_WORK_PHONE  \
0       With parents      -13258          -2300           1                0   
1  House / apartment      -17876           -377           1                1   
2  House / apartment      -19579          -1028           1                0   
3  House / apartment      -15109          -1956           1                0   
4  House / apartment      -17281          -5578           1                1   

   FLAG_PHONE  FLAG_EMAIL                    JOB  BEGIN_MONTHS STATUS  TARGET  
0           0           0               Managers            -6      C       0  
1           1           0  Private service staff            -4      0       0  
2           1           0               Laborers             0      C       0  
3           0           0             Core staff            -3      0       0  
4           0           0                Drivers           -29      0       0

In [3]:
df.isna().any()

ID                     False
CODE_GENDER            False
FLAG_OWN_CAR           False
FLAG_OWN_REALTY        False
CNT_CHILDREN           False
AMT_INCOME_TOTAL       False
NAME_EDUCATION_TYPE    False
NAME_FAMILY_STATUS     False
NAME_HOUSING_TYPE      False
DAYS_BIRTH             False
DAYS_EMPLOYED          False
FLAG_MOBIL             False
FLAG_WORK_PHONE        False
FLAG_PHONE             False
FLAG_EMAIL             False
JOB                    False
BEGIN_MONTHS           False
STATUS                 False
TARGET                 False
dtype: bool

No missing data in all columns.

In [4]:
# Jessie
# CODE_GENDER, FLAG_OWN_CAR, FLAG_OWN_REALTY, CNT_CHILDREN, AMT_INCOME_TOTAL, NAME_INCOME_TYPE, NAME_EDUCATION_TYPE
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler

In [5]:
df['CODE_GENDER'].value_counts()
df['CODE_GENDER']= LabelEncoder().fit_transform(df['CODE_GENDER'])
df['CODE_GENDER']

0         0
1         0
2         1
3         0
4         1
         ..
537662    1
537663    0
537664    1
537665    1
537666    0
Name: CODE_GENDER, Length: 537667, dtype: int64

0 for female and 1 for man

In [6]:
df['FLAG_OWN_CAR'].unique()

array(['Y', 'N'], dtype=object)

In [7]:
df['FLAG_OWN_CAR'] = LabelEncoder().fit_transform(df['FLAG_OWN_CAR'])
df.head()

ID  CODE_GENDER  FLAG_OWN_CAR FLAG_OWN_REALTY CNT_CHILDREN  \
0  5065438            0             1               N  2+ children   
1  5142753            0             0               N  No children   
2  5111146            1             1               Y  No children   
3  5010310            0             1               Y   1 children   
4  5010835            1             1               Y  2+ children   

   AMT_INCOME_TOTAL            NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  \
0          270000.0  Secondary / secondary special               Married   
1           81000.0  Secondary / secondary special  Single / not married   
2          270000.0               Higher education               Married   
3          112500.0  Secondary / secondary special               Married   
4          139500.0  Secondary / secondary special               Married   

   NAME_HOUSING_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  FLAG_MOBIL  FLAG_WORK_PHONE  \
0       With parents      -13258          -2300           1                0   
1  House / apartment      -17876           -377           1                1   
2  House / apartment      -19579          -1028           1                0   
3  House / apartment      -15109          -1956           1                0   
4  House / apartment      -17281          -5578           1                1   

   FLAG_PHONE  FLAG_EMAIL                    JOB  BEGIN_MONTHS STATUS  TARGET  
0           0           0               Managers            -6      C       0  
1           1           0  Private service staff            -4      0       0  
2           1           0               Laborers             0      C       0  
3           0           0             Core staff            -3      0       0  
4           0           0                Drivers           -29      0       0

1 for yes and 0 for no

In [8]:
df['FLAG_OWN_REALTY'].unique()

array(['N', 'Y'], dtype=object)

In [9]:
df['FLAG_OWN_REALTY'] = LabelEncoder().fit_transform(df['FLAG_OWN_REALTY'])
df.head()

ID  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY CNT_CHILDREN  \
0  5065438            0             1                0  2+ children   
1  5142753            0             0                0  No children   
2  5111146            1             1                1  No children   
3  5010310            0             1                1   1 children   
4  5010835            1             1                1  2+ children   

   AMT_INCOME_TOTAL            NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  \
0          270000.0  Secondary / secondary special               Married   
1           81000.0  Secondary / secondary special  Single / not married   
2          270000.0               Higher education               Married   
3          112500.0  Secondary / secondary special               Married   
4          139500.0  Secondary / secondary special               Married   

   NAME_HOUSING_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  FLAG_MOBIL  FLAG_WORK_PHONE  \
0       With parents      -13258          -2300           1                0   
1  House / apartment      -17876           -377           1                1   
2  House / apartment      -19579          -1028           1                0   
3  House / apartment      -15109          -1956           1                0   
4  House / apartment      -17281          -5578           1                1   

   FLAG_PHONE  FLAG_EMAIL                    JOB  BEGIN_MONTHS STATUS  TARGET  
0           0           0               Managers            -6      C       0  
1           1           0  Private service staff            -4      0       0  
2           1           0               Laborers             0      C       0  
3           0           0             Core staff            -3      0       0  
4           0           0                Drivers           -29      0       0

1 for yes and 0 for no

In [10]:
df['CNT_CHILDREN'].unique()

array(['2+ children', 'No children', '1 children'], dtype=object)

To encode the CNT_CHILDREN column as: 0 for "No children," 1 for "1 children," and 2 for "2+ children".

In [11]:
cnt_children_mapping = {
    'No children': 0,
    '1 children': 1,
    '2+ children': 2
}

# Apply the mapping
df['CNT_CHILDREN'] = df['CNT_CHILDREN'].map(cnt_children_mapping)
df.head()

ID  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  CNT_CHILDREN  \
0  5065438            0             1                0             2   
1  5142753            0             0                0             0   
2  5111146            1             1                1             0   
3  5010310            0             1                1             1   
4  5010835            1             1                1             2   

   AMT_INCOME_TOTAL            NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  \
0          270000.0  Secondary / secondary special               Married   
1           81000.0  Secondary / secondary special  Single / not married   
2          270000.0               Higher education               Married   
3          112500.0  Secondary / secondary special               Married   
4          139500.0  Secondary / secondary special               Married   

   NAME_HOUSING_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  FLAG_MOBIL  FLAG_WORK_PHONE  \
0       With parents      -13258          -2300           1                0   
1  House / apartment      -17876           -377           1                1   
2  House / apartment      -19579          -1028           1                0   
3  House / apartment      -15109          -1956           1                0   
4  House / apartment      -17281          -5578           1                1   

   FLAG_PHONE  FLAG_EMAIL                    JOB  BEGIN_MONTHS STATUS  TARGET  
0           0           0               Managers            -6      C       0  
1           1           0  Private service staff            -4      0       0  
2           1           0               Laborers             0      C       0  
3           0           0             Core staff            -3      0       0  
4           0           0                Drivers           -29      0       0

In [12]:
df['AMT_INCOME_TOTAL']

0         270000.0
1          81000.0
2         270000.0
3         112500.0
4         139500.0
            ...   
537662    166500.0
537663    135000.0
537664    180000.0
537665    220500.0
537666    387000.0
Name: AMT_INCOME_TOTAL, Length: 537667, dtype: float64

In [13]:
scaler = StandardScaler()
df['AMT_INCOME_TOTAL'] = scaler.fit_transform(df['AMT_INCOME_TOTAL'].values.reshape(-1, 1))
df.head()

ID  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  CNT_CHILDREN  \
0  5065438            0             1                0             2   
1  5142753            0             0                0             0   
2  5111146            1             1                1             0   
3  5010310            0             1                1             1   
4  5010835            1             1                1             2   

   AMT_INCOME_TOTAL            NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  \
0          0.699862  Secondary / secondary special               Married   
1         -1.115022  Secondary / secondary special  Single / not married   
2          0.699862               Higher education               Married   
3         -0.812541  Secondary / secondary special               Married   
4         -0.553272  Secondary / secondary special               Married   

   NAME_HOUSING_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  FLAG_MOBIL  FLAG_WORK_PHONE  \
0       With parents      -13258          -2300           1                0   
1  House / apartment      -17876           -377           1                1   
2  House / apartment      -19579          -1028           1                0   
3  House / apartment      -15109          -1956           1                0   
4  House / apartment      -17281          -5578           1                1   

   FLAG_PHONE  FLAG_EMAIL                    JOB  BEGIN_MONTHS STATUS  TARGET  
0           0           0               Managers            -6      C       0  
1           1           0  Private service staff            -4      0       0  
2           1           0               Laborers             0      C       0  
3           0           0             Core staff            -3      0       0  
4           0           0                Drivers           -29      0       0

In [14]:
# use ordinal encoding for NAME_EDUCATION_TYPE
df['NAME_EDUCATION_TYPE'].unique()

array(['Secondary / secondary special', 'Higher education',
       'Incomplete higher', 'Lower secondary', 'Academic degree'],
      dtype=object)

In [15]:
name_education_type_mapping = {
    'Lower secondary': 0,
    'Secondary / secondary special': 1,
    'Incomplete higher': 2,
    'Higher education': 3,
    'Academic degree': 4
}
df['NAME_EDUCATION_TYPE'] = df['NAME_EDUCATION_TYPE'].map(name_education_type_mapping)
df.head()

ID  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  CNT_CHILDREN  \
0  5065438            0             1                0             2   
1  5142753            0             0                0             0   
2  5111146            1             1                1             0   
3  5010310            0             1                1             1   
4  5010835            1             1                1             2   

   AMT_INCOME_TOTAL  NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  \
0          0.699862                    1               Married   
1         -1.115022                    1  Single / not married   
2          0.699862                    3               Married   
3         -0.812541                    1               Married   
4         -0.553272                    1               Married   

   NAME_HOUSING_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  FLAG_MOBIL  FLAG_WORK_PHONE  \
0       With parents      -13258          -2300           1                0   
1  House / apartment      -17876           -377           1                1   
2  House / apartment      -19579          -1028           1                0   
3  House / apartment      -15109          -1956           1                0   
4  House / apartment      -17281          -5578           1                1   

   FLAG_PHONE  FLAG_EMAIL                    JOB  BEGIN_MONTHS STATUS  TARGET  
0           0           0               Managers            -6      C       0  
1           1           0  Private service staff            -4      0       0  
2           1           0               Laborers             0      C       0  
3           0           0             Core staff            -3      0       0  
4           0           0                Drivers           -29      0       0

In [16]:
# Bobby
# NAME_FAMILY_STATUS, NAME_HOUSING_TYPE, DAYS_BIRTH, DAYS_EMPLOYED, FLAG_MOBIL, FLAG_WORK_PHONE

In [17]:
# NAME_FAMILY_STATUS
df['NAME_FAMILY_STATUS'].unique()

array(['Married', 'Single / not married', 'Civil marriage', 'Separated',
       'Widow'], dtype=object)

In [18]:
df = pd.get_dummies(df, columns=['NAME_FAMILY_STATUS'], prefix='FAMILY_STATUS')
df

ID  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  CNT_CHILDREN  \
0       5065438            0             1                0             2   
1       5142753            0             0                0             0   
2       5111146            1             1                1             0   
3       5010310            0             1                1             1   
4       5010835            1             1                1             2   
...         ...          ...           ...              ...           ...   
537662  5142999            1             1                0             1   
537663  5010773            0             0                1             0   
537664  5105601            1             0                1             0   
537665  5132833            1             1                0             0   
537666  5135381            0             0                1             0   

        AMT_INCOME_TOTAL  NAME_EDUCATION_TYPE  NAME_HOUSING_TYPE  DAYS_BIRTH  \
0               0.699862                    1       With parents      -13258   
1              -1.115022                    1  House / apartment      -17876   
2               0.699862                    3  House / apartment      -19579   
3              -0.812541                    1  House / apartment      -15109   
4              -0.553272                    1  House / apartment      -17281   
...                  ...                  ...                ...         ...   
537662         -0.294003                    1       With parents      -12372   
537663         -0.596484                    3       With parents      -14160   
537664         -0.164368                    3  House / apartment      -24204   
537665          0.224536                    1  House / apartment      -22647   
537666          1.823362                    1  House / apartment      -20082   

        DAYS_EMPLOYED  ...  FLAG_EMAIL                    JOB  BEGIN_MONTHS  \
0               -2300  ...           0               Managers            -6   
1                -377  ...           0  Private service staff            -4   
2               -1028  ...           0               Laborers             0   
3               -1956  ...           0             Core staff            -3   
4               -5578  ...           0                Drivers           -29   
...               ...  ...         ...                    ...           ...   
537662          -5401  ...           0             Core staff            -8   
537663          -4635  ...           0            Sales staff            -8   
537664          -2462  ...           0  Private service staff            -7   
537665          -3847  ...           0               Laborers            -1   
537666          -4979  ...           0            Sales staff           -45   

        STATUS TARGET  FAMILY_STATUS_Civil marriage FAMILY_STATUS_Married  \
0            C      0                         False                  True   
1            0      0                         False                 False   
2            C      0                         False                  True   
3            0      0                         False                  True   
4            0      0                         False                  True   
...        ...    ...                           ...                   ...   
537662       0      0                         False                  True   
537663       0      0                         False                  True   
537664       0      0                         False                  True   
537665       0      0                         False                  True   
537666       C      0                         False                  True   

        FAMILY_STATUS_Separated  FAMILY_STATUS_Single / not married  \
0                         False                               False   
1                         False                                True   
2                         False         

In [19]:
# NAME_HOUSING_TYPE
df['NAME_HOUSING_TYPE'].unique()

array(['With parents', 'House / apartment', 'Rented apartment',
       'Municipal apartment', 'Co-op apartment', 'Office apartment'],
      dtype=object)

In [20]:
df = pd.get_dummies(df, columns=['NAME_HOUSING_TYPE'], prefix='HOUSING_TYPE')
df

ID  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  CNT_CHILDREN  \
0       5065438            0             1                0             2   
1       5142753            0             0                0             0   
2       5111146            1             1                1             0   
3       5010310            0             1                1             1   
4       5010835            1             1                1             2   
...         ...          ...           ...              ...           ...   
537662  5142999            1             1                0             1   
537663  5010773            0             0                1             0   
537664  5105601            1             0                1             0   
537665  5132833            1             1                0             0   
537666  5135381            0             0                1             0   

        AMT_INCOME_TOTAL  NAME_EDUCATION_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  \
0               0.699862                    1      -13258          -2300   
1              -1.115022                    1      -17876           -377   
2               0.699862                    3      -19579          -1028   
3              -0.812541                    1      -15109          -1956   
4              -0.553272                    1      -17281          -5578   
...                  ...                  ...         ...            ...   
537662         -0.294003                    1      -12372          -5401   
537663         -0.596484                    3      -14160          -4635   
537664         -0.164368                    3      -24204          -2462   
537665          0.224536                    1      -22647          -3847   
537666          1.823362                    1      -20082          -4979   

        FLAG_MOBIL  ...  FAMILY_STATUS_Married  FAMILY_STATUS_Separated  \
0                1  ...                   True                    False   
1                1  ...                  False                    False   
2                1  ...                   True                    False   
3                1  ...                   True                    False   
4                1  ...                   True                    False   
...            ...  ...                    ...                      ...   
537662           1  ...                   True                    False   
537663           1  ...                   True                    False   
537664           1  ...                   True                    False   
537665           1  ...                   True                    False   
537666           1  ...                   True                    False   

        FAMILY_STATUS_Single / not married FAMILY_STATUS_Widow  \
0                                    False               False   
1                                     True               False   
2                                    False               False   
3                                    False               False   
4                                    False               False   
...                                    ...                 ...   
537662                               False               False   
537663                               False               False   
537664                               False               False   
537665                               False               False   
537666                               False               False   

        HOUSING_TYPE_Co-op apartment HOUSING_TYPE_House / apartment  \
0                              False                          False   
1                              False                           True   
2                              False                           True   
3                              False                           True   
4                              False                           True   
...                              ...                   

In [21]:
# DAYS_BIRTH
df['DAYS_BIRTH'].unique()

array([-13258, -17876, -19579, ...,  -7489, -20216, -20806])

In [22]:
print(f"DAYS_BIRTH's max is {max(df['DAYS_BIRTH'])}")
print(f"DAYS_BIRTH's min is {min(df['DAYS_BIRTH'])}")

DAYS_BIRTH's max is -7489
DAYS_BIRTH's min is -24611


In [23]:
scaler = StandardScaler()
df['DAYS_BIRTH'] = scaler.fit_transform(df['DAYS_BIRTH'].values.reshape(-1, 1))
df['DAYS_BIRTH']

0         0.513099
1        -0.838610
2        -1.337086
3        -0.028697
4        -0.664451
            ...   
537662    0.772435
537663    0.249080
537664   -2.690844
537665   -2.235104
537666   -1.484316
Name: DAYS_BIRTH, Length: 537667, dtype: float64

In [24]:
# DAYS_EMPLOYED
df['DAYS_EMPLOYED'].unique()

array([-2300,  -377, -1028, ..., -4420,  -797, -7765])

In [25]:
scaler = MinMaxScaler()
df['DAYS_EMPLOYED'] = scaler.fit_transform(df['DAYS_EMPLOYED'].values.reshape(-1, 1))
df['DAYS_EMPLOYED']

0         0.854549
1         0.977064
2         0.935589
3         0.876465
4         0.645706
            ...   
537662    0.656983
537663    0.705785
537664    0.844228
537665    0.755989
537666    0.683869
Name: DAYS_EMPLOYED, Length: 537667, dtype: float64

In [26]:
# FLAG_MOBIL
df['FLAG_MOBIL'].unique()

array([1])

In [27]:
df = df.drop(columns=["FLAG_MOBIL"])
df.head(5)

ID  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  CNT_CHILDREN  \
0  5065438            0             1                0             2   
1  5142753            0             0                0             0   
2  5111146            1             1                1             0   
3  5010310            0             1                1             1   
4  5010835            1             1                1             2   

   AMT_INCOME_TOTAL  NAME_EDUCATION_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  \
0          0.699862                    1    0.513099       0.854549   
1         -1.115022                    1   -0.838610       0.977064   
2          0.699862                    3   -1.337086       0.935589   
3         -0.812541                    1   -0.028697       0.876465   
4         -0.553272                    1   -0.664451       0.645706   

   FLAG_WORK_PHONE  ...  FAMILY_STATUS_Married  FAMILY_STATUS_Separated  \
0                0  ...                   True                    False   
1                1  ...                  False                    False   
2                0  ...                   True                    False   
3                0  ...                   True                    False   
4                1  ...                   True                    False   

  FAMILY_STATUS_Single / not married  FAMILY_STATUS_Widow  \
0                              False                False   
1                               True                False   
2                              False                False   
3                              False                False   
4                              False                False   

  HOUSING_TYPE_Co-op apartment  HOUSING_TYPE_House / apartment  \
0                        False                           False   
1                        False                            True   
2                        False                            True   
3                        False                            True   
4                        False                            True   

   HOUSING_TYPE_Municipal apartment  HOUSING_TYPE_Office apartment  \
0                             False                          False   
1                             False                          False   
2                             False                          False   
3                             False                          False   
4                             False                          False   

   HOUSING_TYPE_Rented apartment  HOUSING_TYPE_With parents  
0                          False                       True  
1                          False                      False  
2                          False                      False  
3                          False                      False  
4                          False                      False  

[5 rows x 27 columns]

In [28]:
# FLAG_WORK_PHONE
df['FLAG_WORK_PHONE'].unique()

array([0, 1])

In [29]:
# Will
# FLAG_PHONE, FLAG_EMAIL, JOB, BEGIN_MONTHS, STATUS

In [30]:
# FLAG_PHONE
df['FLAG_PHONE'].unique()

array([0, 1])

In [31]:
# FLAG_EMAIL
df['FLAG_EMAIL'].unique()

array([0, 1])

In [32]:
# JOB
df['JOB'].unique()

array(['Managers', 'Private service staff', 'Laborers', 'Core staff',
       'Drivers', 'High skill tech staff', 'Realty agents', 'Secretaries',
       'Accountants', 'Sales staff', 'Medicine staff',
       'Waiters/barmen staff', 'Low-skill Laborers', 'Cleaning staff',
       'HR staff', 'Cooking staff', 'Security staff', 'IT staff'],
      dtype=object)

In [33]:
df = pd.get_dummies(df, columns=['JOB'], prefix='JOB')
df.head()

ID  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  CNT_CHILDREN  \
0  5065438            0             1                0             2   
1  5142753            0             0                0             0   
2  5111146            1             1                1             0   
3  5010310            0             1                1             1   
4  5010835            1             1                1             2   

   AMT_INCOME_TOTAL  NAME_EDUCATION_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  \
0          0.699862                    1    0.513099       0.854549   
1         -1.115022                    1   -0.838610       0.977064   
2          0.699862                    3   -1.337086       0.935589   
3         -0.812541                    1   -0.028697       0.876465   
4         -0.553272                    1   -0.664451       0.645706   

   FLAG_WORK_PHONE  ...  JOB_Laborers  JOB_Low-skill Laborers  JOB_Managers  \
0                0  ...         False                   False          True   
1                1  ...         False                   False         False   
2                0  ...          True                   False         False   
3                0  ...         False                   False         False   
4                1  ...         False                   False         False   

  JOB_Medicine staff  JOB_Private service staff  JOB_Realty agents  \
0              False                      False              False   
1              False                       True              False   
2              False                      False              False   
3              False                      False              False   
4              False                      False              False   

   JOB_Sales staff  JOB_Secretaries  JOB_Security staff  \
0            False            False               False   
1            False            False               False   
2            False            False               False   
3            False            False               False   
4            False            False               False   

   JOB_Waiters/barmen staff  
0                     False  
1                     False  
2                     False  
3                     False  
4                     False  

[5 rows x 44 columns]

In [34]:
# BEGIN_MONTHS
df['BEGIN_MONTHS'].unique()

array([ -6,  -4,   0,  -3, -29, -25, -19, -18, -43, -38, -15, -30, -26,
        -8, -39, -12, -52,  -7, -20, -35, -32,  -2, -11, -10, -13, -33,
       -34, -31,  -1, -23, -27, -22, -28,  -5, -36,  -9, -16, -14, -17,
       -24, -37, -44, -47, -48, -21, -42, -50, -51, -54, -40, -41, -55,
       -46, -58, -49, -53, -56, -57, -45, -59, -60])

In [35]:
scaler = StandardScaler()
df['BEGIN_MONTHS'] = scaler.fit_transform(df[['BEGIN_MONTHS']].values.reshape(-1, 1))
df.head()

ID  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  CNT_CHILDREN  \
0  5065438            0             1                0             2   
1  5142753            0             0                0             0   
2  5111146            1             1                1             0   
3  5010310            0             1                1             1   
4  5010835            1             1                1             2   

   AMT_INCOME_TOTAL  NAME_EDUCATION_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  \
0          0.699862                    1    0.513099       0.854549   
1         -1.115022                    1   -0.838610       0.977064   
2          0.699862                    3   -1.337086       0.935589   
3         -0.812541                    1   -0.028697       0.876465   
4         -0.553272                    1   -0.664451       0.645706   

   FLAG_WORK_PHONE  ...  JOB_Laborers  JOB_Low-skill Laborers  JOB_Managers  \
0                0  ...         False                   False          True   
1                1  ...         False                   False         False   
2                0  ...          True                   False         False   
3                0  ...         False                   False         False   
4                1  ...         False                   False         False   

  JOB_Medicine staff  JOB_Private service staff  JOB_Realty agents  \
0              False                      False              False   
1              False                       True              False   
2              False                      False              False   
3              False                      False              False   
4              False                      False              False   

   JOB_Sales staff  JOB_Secretaries  JOB_Security staff  \
0            False            False               False   
1            False            False               False   
2            False            False               False   
3            False            False               False   
4            False            False               False   

   JOB_Waiters/barmen staff  
0                     False  
1                     False  
2                     False  
3                     False  
4                     False  

[5 rows x 44 columns]

In [36]:
df['BEGIN_MONTHS']

0         0.947814
1         1.090287
2         1.375231
3         1.161523
4        -0.690617
            ...   
537662    0.805342
537663    0.805342
537664    0.876578
537665    1.303995
537666   -1.830396
Name: BEGIN_MONTHS, Length: 537667, dtype: float64

In [37]:
# STATUS
df['STATUS'].unique()

array(['C', '0', 'X', '2', '1', '5', '3', '4'], dtype=object)

In [38]:
# Ordinal mapping
status_mapping = {
    '0': 0,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    'C': -1,  # Paid off
    'X': -2   # No loan
}
df['STATUS'] = df['STATUS'].map(status_mapping)
df['STATUS']

0        -1
1         0
2        -1
3         0
4         0
         ..
537662    0
537663    0
537664    0
537665    0
537666   -1
Name: STATUS, Length: 537667, dtype: int64

In [39]:
# Count the number of 0s and 1s for the TARGET column
target_counts = df['TARGET'].value_counts()
print(target_counts)

TARGET
0    535705
1      1962
Name: count, dtype: int64


In [40]:
df.head()

ID  CODE_GENDER  FLAG_OWN_CAR  FLAG_OWN_REALTY  CNT_CHILDREN  \
0  5065438            0             1                0             2   
1  5142753            0             0                0             0   
2  5111146            1             1                1             0   
3  5010310            0             1                1             1   
4  5010835            1             1                1             2   

   AMT_INCOME_TOTAL  NAME_EDUCATION_TYPE  DAYS_BIRTH  DAYS_EMPLOYED  \
0          0.699862                    1    0.513099       0.854549   
1         -1.115022                    1   -0.838610       0.977064   
2          0.699862                    3   -1.337086       0.935589   
3         -0.812541                    1   -0.028697       0.876465   
4         -0.553272                    1   -0.664451       0.645706   

   FLAG_WORK_PHONE  ...  JOB_Laborers  JOB_Low-skill Laborers  JOB_Managers  \
0                0  ...         False                   False          True   
1                1  ...         False                   False         False   
2                0  ...          True                   False         False   
3                0  ...         False                   False         False   
4                1  ...         False                   False         False   

   JOB_Medicine staff  JOB_Private service staff  JOB_Realty agents  \
0               False                      False              False   
1               False                       True              False   
2               False                      False              False   
3               False                      False              False   
4               False                      False              False   

   JOB_Sales staff  JOB_Secretaries  JOB_Security staff  \
0            False            False               False   
1            False            False               False   
2            False            False               False   
3            False            False               False   
4            False            False               False   

   JOB_Waiters/barmen staff  
0                     False  
1                     False  
2                     False  
3                     False  
4                     False  

[5 rows x 44 columns]

In [41]:
df.isna().any()

ID                                    False
CODE_GENDER                           False
FLAG_OWN_CAR                          False
FLAG_OWN_REALTY                       False
CNT_CHILDREN                          False
AMT_INCOME_TOTAL                      False
NAME_EDUCATION_TYPE                   False
DAYS_BIRTH                            False
DAYS_EMPLOYED                         False
FLAG_WORK_PHONE                       False
FLAG_PHONE                            False
FLAG_EMAIL                            False
BEGIN_MONTHS                          False
STATUS                                False
TARGET                                False
FAMILY_STATUS_Civil marriage          False
FAMILY_STATUS_Married                 False
FAMILY_STATUS_Separated               False
FAMILY_STATUS_Single / not married    False
FAMILY_STATUS_Widow                   False
HOUSING_TYPE_Co-op apartment          False
HOUSING_TYPE_House / apartment        False
HOUSING_TYPE_Municipal apartment      False
HOUSING_TYPE_Office apartment         False
HOUSING_TYPE_Rented apartment         False
HOUSING_TYPE_With parents             False
JOB_Accountants                       False
JOB_Cleaning staff                    False
JOB_Cooking staff                     False
JOB_Core staff                        False
JOB_Drivers                           False
JOB_HR staff                          False
JOB_High skill tech staff             False
JOB_IT staff                          False
JOB_Laborers                          False
JOB_Low-skill Laborers                False
JOB_Managers                          False
JOB_Medicine staff                    False
JOB_Private service staff             False
JOB_Realty agents                     False
JOB_Sales staff                       False
JOB_Secretaries                       False
JOB_Security staff                    False
JOB_Waiters/barmen staff              False
dtype: bool

In [42]:
df.columns

Index(['ID', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'NAME_EDUCATION_TYPE', 'DAYS_BIRTH',
       'DAYS_EMPLOYED', 'FLAG_WORK_PHONE', 'FLAG_PHONE', 'FLAG_EMAIL',
       'BEGIN_MONTHS', 'STATUS', 'TARGET', 'FAMILY_STATUS_Civil marriage',
       'FAMILY_STATUS_Married', 'FAMILY_STATUS_Separated',
       'FAMILY_STATUS_Single / not married', 'FAMILY_STATUS_Widow',
       'HOUSING_TYPE_Co-op apartment', 'HOUSING_TYPE_House / apartment',
       'HOUSING_TYPE_Municipal apartment', 'HOUSING_TYPE_Office apartment',
       'HOUSING_TYPE_Rented apartment', 'HOUSING_TYPE_With parents',
       'JOB_Accountants', 'JOB_Cleaning staff', 'JOB_Cooking staff',
       'JOB_Core staff', 'JOB_Drivers', 'JOB_HR staff',
       'JOB_High skill tech staff', 'JOB_IT staff', 'JOB_Laborers',
       'JOB_Low-skill Laborers', 'JOB_Managers', 'JOB_Medicine staff',
       'JOB_Private service staff', 'JOB_Realty agents', 'JOB_Sales staff',
       'JOB_Secretaries', 

This is all preprocess steps.

---

Begin training our first model.

In [43]:
# Use logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score

In [44]:
# Define X (independent variables) and y (dependent variable)
X = df.drop(columns=['ID', 'TARGET'])  # Drop ID and TARGET for features
y = df['TARGET']  # TARGET column as the target variable

# One-hot encode categorical columns
X = pd.get_dummies(X, drop_first=True)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

# Initialize and fit the logistic regression model
model = LogisticRegression(class_weight='balanced', max_iter=1000)  # Increase max_iter if convergence warnings occur
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

X_train shape: (376366, 42)
X_test shape: (161301, 42)
y_train shape: (376366,)
y_test shape: (161301,)
Accuracy: 1.0000

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    160712
           1       0.99      1.00      1.00       589

    accuracy                           1.00    161301
   macro avg       1.00      1.00      1.00    161301
weighted avg       1.00      1.00      1.00    161301


Confusion Matrix:
 [[160707      5]
 [     0    589]]


In [45]:
# Verify that the features (X) do not contain any columns derived from
# the target (TARGET) or any feature that trivially predicts it.
print(X.corrwith(y))

CODE_GENDER                           0.016732
FLAG_OWN_CAR                          0.003076
FLAG_OWN_REALTY                       0.005364
CNT_CHILDREN                          0.000234
AMT_INCOME_TOTAL                      0.002887
NAME_EDUCATION_TYPE                   0.005019
DAYS_BIRTH                           -0.005401
DAYS_EMPLOYED                         0.019230
FLAG_WORK_PHONE                       0.004353
FLAG_PHONE                            0.008663
FLAG_EMAIL                           -0.001807
BEGIN_MONTHS                         -0.001646
STATUS                                0.350245
FAMILY_STATUS_Civil marriage         -0.011115
FAMILY_STATUS_Married                -0.002681
FAMILY_STATUS_Separated              -0.004678
FAMILY_STATUS_Single / not married    0.013763
FAMILY_STATUS_Widow                   0.005650
HOUSING_TYPE_Co-op apartment          0.006855
HOUSING_TYPE_House / apartment       -0.004141
HOUSING_TYPE_Municipal apartment      0.005352
HOUSING_TYPE_

In [46]:
# Use k-fold cross-validation to ensure the performance
# generalizes across different splits of the dataset
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, X, y, cv=5, scoring='accuracy')
print("Cross-validated accuracy: ", scores.mean())

Cross-validated accuracy:  0.9999758214968348


In [47]:
# Train error
y_train_pred = model.predict(X_train)
train_accuracy = accuracy_score(y_train, y_train_pred)
print(f"Train Accuracy: {train_accuracy:.4f}")
print("\nTrain Classification Report:\n", classification_report(y_train, y_train_pred))
print("\nTrain Confusion Matrix:\n", confusion_matrix(y_train, y_train_pred))

Train Accuracy: 1.0000

Train Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00    374993
           1       0.99      1.00      1.00      1373

    accuracy                           1.00    376366
   macro avg       1.00      1.00      1.00    376366
weighted avg       1.00      1.00      1.00    376366


Train Confusion Matrix:
 [[374985      8]
 [     0   1373]]
